version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-www-traefik-app:
    image: "ghassanaldarwish/wds-www"
    restart: always
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-www-traefik-app.rule=Host(`webdrei.com`)"
      - "traefik.http.routers.wds-www-traefik-app.entrypoints=websecure"
      - "traefik.http.routers.wds-www-traefik-app.tls.certresolver=cloudflare"
      - traefik.http.routers.wds-www-traefik-app.tls=true
      # - traefik.http.routers.wds-www-traefik-app.tls.domains[0].main=webdrei.com
      # - traefik.http.routers.wds-www-traefik-app.tls.domains[0].sans=*.webdrei.com
      - "traefik.http.services.wds-www-traefik-app.loadbalancer.server.port=3000"
    env_file:
      - ../environment/wds-www/.env.local

networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
