version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-www-nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-www-nginx.rule=Host(`webdrei.com`)"
      - "traefik.http.routers.wds-www-nginx.entrypoints=websecure"
      - "traefik.http.routers.wds-www-nginx.tls.certresolver=letsencrypt"
      - traefik.http.routers.wds-www-nginx.tls=true
      - traefik.http.routers.wds-www-nginx.tls.domains[0].main=webdrei.com
      - traefik.http.routers.wds-www-nginx.tls.domains[0].sans=*.webdrei.com
      - "traefik.http.services.wds-www-nginx.loadbalancer.server.port=80"
    networks:
      - app-workspace-network
      - frontend

  wds-www:
    image: "ghassanaldarwish/wds-www"
    restart: on-failure
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production

    env_file:
      - ../environment/wds-www/.env.local

networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
